export const currencies = [
  { value: "USD", label: "United States Dollar" },
  { value: "EUR", label: "Euro" },
  { value: "JPY", label: "Japanese Yen" },
  { value: "GBP", label: "British Pound Sterling" },
  { value: "AUD", label: "Australian Dollar" },
  { value: "CAD", label: "Canadian Dollar" },
  { value: "CHF", label: "Swiss Franc" },
  { value: "CNY", label: "Chinese Yuan" },
  { value: "SEK", label: "Swedish Krona" },
  { value: "NZD", label: "New Zealand Dollar" },
  { value: "MXN", label: "Mexican Peso" },
  { value: "SGD", label: "Singapore Dollar" },
  { value: "HKD", label: "Hong Kong Dollar" },
  { value: "NOK", label: "Norwegian Krone" },
  { value: "KRW", label: "South Korean Won" },
  { value: "TRY", label: "Turkish Lira" },
  { value: "RUB", label: "Russian Ruble" },
  { value: "INR", label: "Indian Rupee" },
  { value: "BRL", label: "Brazilian Real" },
  { value: "ZAR", label: "South African Rand" },
  { value: "PLN", label: "Polish Zloty" },
  { value: "PHP", label: "Philippine Peso" },
  { value: "IDR", label: "Indonesian Rupiah" },
  { value: "HUF", label: "Hungarian Forint" },
  { value: "CZK", label: "Czech Koruna" },
  { value: "ILS", label: "Israeli New Shekel" },
  { value: "MYR", label: "Malaysian Ringgit" },
  { value: "THB", label: "Thai Baht" },
  { value: "PKR", label: "Pakistani Rupee" },
  { value: "EGP", label: "Egyptian Pound" },
  { value: "SAR", label: "Saudi Riyal" },
  { value: "AED", label: "United Arab Emirates Dirham" },
  { value: "KWD", label: "Kuwaiti Dinar" },
  { value: "QAR", label: "Qatari Riyal" },
  { value: "DKK", label: "Danish Krone" },
  { value: "BGN", label: "Bulgarian Lev" },
  { value: "RON", label: "Romanian Leu" },
  { value: "ARS", label: "Argentine Peso" },
  { value: "CLP", label: "Chilean Peso" },
  { value: "COP", label: "Colombian Peso" },
  { value: "PEN", label: "Peruvian Sol" },
  { value: "VND", label: "Vietnamese Dong" },
  { value: "NGN", label: "Nigerian Naira" },
  { value: "GHS", label: "Ghanaian Cedi" },
  { value: "XOF", label: "West African CFA Franc" },
  { value: "XAF", label: "Central African CFA Franc" },
  { value: "KES", label: "Kenyan Shilling" },
  { value: "TZS", label: "Tanzanian Shilling" },
  { value: "UGX", label: "Ugandan Shilling" },
  { value: "BHD", label: "Bahraini Dinar" },
  { value: "OMR", label: "Omani Rial" },
  { value: "TND", label: "Tunisian Dinar" },
  { value: "MAD", label: "Moroccan Dirham" }
];
