export function useLocalizatedCategories(categoryName: string, locale: string) {
  const localizedCategories = {
    ru: {
      "Food": "Еда",
      "Transport": "Транспорт",
      "Home": "Дом",
      "Health": "Здоровье",
      "Family": "Семья",
      "Fastfood": "Фастфуд",
      "Bar": "Бар",
      "Car": "Машина",
      "Fuel": "Топливо",
      "Travel Transport": "Путешествия (транспорт)",
      "Shopping": "Шоппинг",
      "Clothing": "Одежда",
      "Footwear": "Обувь",
      "Technology": "Технологии",
      "Entertainment": "Развлечения",
      "Rental Bill": "Арендная плата",
      "Energy Bill": "Счет за электроэнергию",
      "Water Bill": "Счет за воду",
      "Waste Bill": "Счет за вывоз мусора",
      "Kids": "Дети",
      "Education": "Образование",
      "Pets": "Домашние животные",
      "Pet Food": "Корм для животных",
      "Gifts": "Подарки",
      "Taxes": "Налоги",
      "Other (Expenses)": "Прочие расходы"
    },
    ua: {
      "Food": "Їжа",
      "Transport": "Транспорт",
      "Home": "Дім",
      "Health": "Здоров'я",
      "Family": "Сім'я",
      "Fastfood": "Фастфуд",
      "Bar": "Бар",
      "Car": "Автомобіль",
      "Fuel": "Паливо",
      "Travel Transport": "Подорожі (транспорт)",
      "Shopping": "Шопінг",
      "Clothing": "Одяг",
      "Footwear": "Взуття",
      "Technology": "Технології",
      "Entertainment": "Розваги",
      "Rental Bill": "Оренда",
      "Energy Bill": "Счет за електроенергію",
      "Water Bill": "Счет за воду",
      "Waste Bill": "Счет за вивіз сміття",
      "Kids": "Діти",
      "Education": "Освіта",
      "Pets": "Домашні тварини",
      "Pet Food": "Їжа для тварин",
      "Gifts": "Подарунки",
      "Taxes": "Податки",
      "Other (Expenses)": "Інші витрати"
    },
    en: {
      "Food": "Food",
      "Transport": "Transport",
      "Home": "Home",
      "Health": "Health",
      "Family": "Family",
      "Fastfood": "Fastfood",
      "Bar": "Bar",
      "Car": "Car",
      "Fuel": "Fuel",
      "Travel Transport": "Travel Transport",
      "Shopping": "Shopping",
      "Clothing": "Clothing",
      "Footwear": "Footwear",
      "Technology": "Technology",
      "Entertainment": "Entertainment",
      "Rental Bill": "Rental Bill",
      "Energy Bill": "Energy Bill",
      "Water Bill": "Water Bill",
      "Waste Bill": "Waste Bill",
      "Kids": "Kids",
      "Education": "Education",
      "Pets": "Pets",
      "Pet Food": "Pet Food",
      "Gifts": "Gifts",
      "Taxes": "Taxes",
      "Other (Expenses)": "Other (Expenses)"
    },
    de: {
      "Food": "Essen",
      "Transport": "Transport",
      "Home": "Zuhause",
      "Health": "Gesundheit",
      "Family": "Familie",
      "Fastfood": "Fastfood",
      "Bar": "Bar",
      "Car": "Auto",
      "Fuel": "Benzin",
      "Travel Transport": "Reise Transport",
      "Shopping": "Einkaufen",
      "Clothing": "Kleidung",
      "Footwear": "Schuhe",
      "Technology": "Technologie",
      "Entertainment": "Unterhaltung",
      "Rental Bill": "Mietrechnung",
      "Energy Bill": "Stromrechnung",
      "Water Bill": "Wasserrechnung",
      "Waste Bill": "Abfallgebühren",
      "Kids": "Kinder",
      "Education": "Bildung",
      "Pets": "Haustiere",
      "Pet Food": "Haustierfutter",
      "Gifts": "Geschenke",
      "Taxes": "Steuern",
      "Other (Expenses)": "Sonstige Ausgaben"
    }
  };

  return localizedCategories[locale]?.[categoryName] || categoryName;
}